import { db, storiesTable } from "@workspace/db";

const seededStories = [
  {
    slug: "the-lunch-line-is-a-map",
    category: "school lunch",
    title: "The lunch line is a map of who gets looked after",
    excerpt: "What happens when we stop treating a cafeteria like a checkout counter—and start treating it like a commons?",
    date: "2024-10-17",
    readTimeMinutes: 7,
    author: "Maya Chen",
    body: [
      "At 12:14, the lunch line becomes a map. You can see who has time, who is saving a seat, who knows which tray has the good fruit, and who is moving quickly because they have somewhere else to be.",
      "We talk about food waste like it is a pile, a statistic, a problem with a tidy edge. At school, it is more ordinary than that. It is the unopened milk. The apple that rolls under the bench. The extra slice that nobody wanted until somebody asks.",
      "A full table is not a reward for getting everything right. It is how we practice looking after each other.",
      "The fix is not a perfect lunchroom. Perfect systems are mostly an excuse to wait. The fix is a second bin, labeled clearly. A shelf with a sign that says take what you need. A student willing to ask the cafeteria team what happens to the food at the end of the day—and willing to listen to the answer.",
      "We started small. Every Thursday, two of us stay ten minutes after the bell. We log what is left, pack what can be packed, and call the community fridge on Oak Street. The first week, it was three containers. Last week, it was nineteen. The number matters less than the habit: food does not disappear just because the bell rings.",
      "There is no gold star at the end of this. Just better odds. Better odds that someone gets dinner. Better odds that the work of growing, cooking, and carrying food is treated with the respect it deserves. Better odds that when we say “everyone,” we mean the person sitting beside us.",
    ].join("\n\n"),
    tags: ["schoollunch", "mutualaid", "startsmall"],
    status: "published",
    publishedAt: new Date("2024-10-17T12:00:00.000Z"),
  },
  {
    slug: "leftovers-have-a-second-life",
    category: "leftovers",
    title: "Leftovers have a second life. We just have to make room for it.",
    excerpt: "A practical, unglamorous guide to the food that waits in the back of the fridge.",
    date: "2024-10-08",
    readTimeMinutes: 4,
    author: "Ari Okafor",
    body: [
      "The back of the fridge is not a graveyard. It is a waiting room.",
      "Start by making the container easy to see. Put leftovers at eye level, give them a generous label, and decide on one night each week when everyone eats what is already there. The habit is less glamorous than a new recipe, but it is much more useful.",
      "A scoop of rice can become a crisp-edged breakfast. Roasted vegetables can fill a sandwich. Half a jar of sauce can turn a lonely can of beans into dinner. The point is not to make yesterday disappear. It is to give it another shape.",
      "Make room for the second life. It is usually closer than you think.",
    ].join("\n\n"),
    tags: ["leftovers", "kitchen", "usewhatyouhave"],
    status: "published",
    publishedAt: new Date("2024-10-08T12:00:00.000Z"),
  },
  {
    slug: "the-fridge-between-us",
    category: "mutual aid",
    title: "The fridge between us",
    excerpt: "Inside our school’s tiny, unofficial food shelf—and the students keeping it stocked.",
    date: "2024-09-26",
    readTimeMinutes: 6,
    author: "Noor Rahman",
    body: [
      "The community fridge started with a handwritten sign and a question: what would it look like if taking food did not require explaining why you needed it?",
      "Now it sits by the library, stocked by students, cafeteria staff, and neighbors. There are apples beside soup, granola bars beside notes, and always one thing that someone brought because they knew another person might be looking for it.",
      "Mutual aid is not charity with better branding. It is a practice of noticing what is available and making access ordinary. The shelf works because nobody owns the whole solution.",
      "By Friday afternoon, the fridge is often empty. That is not failure. It means the food moved where it needed to go.",
    ].join("\n\n"),
    tags: ["mutualaid", "communityfridge", "access"],
    status: "published",
    publishedAt: new Date("2024-09-26T12:00:00.000Z"),
  },
  {
    slug: "five-ways-to-rescue-a-banana",
    category: "food rescue",
    title: "Five ways to rescue a banana on the brink",
    excerpt: "No recipe voiceover. No moral lecture. Just five good exits for a speckled banana.",
    date: "2024-09-14",
    readTimeMinutes: 3,
    author: "Leo Williams",
    body: [
      "A brown banana is not a bad banana. It is a banana with a shorter list of jobs left to do.",
      "Blend it with oats. Mash it into toast. Freeze it for a smoothie. Stir it into pancake batter. Or peel it, slice it, and freeze the slices for the next person who needs a quick breakfast.",
      "Rescue is not about squeezing one more perfect day out of every piece of food. It is about noticing the useful days that are still there.",
    ].join("\n\n"),
    tags: ["foodrescue", "bananas", "smallwins"],
    status: "published",
    publishedAt: new Date("2024-09-14T12:00:00.000Z"),
  },
  {
    slug: "ask-for-the-extra-serving",
    category: "student action",
    title: "Ask for the extra serving",
    excerpt: "The most useful thing you can do this week might be a question asked at the right volume.",
    date: "2024-09-04",
    readTimeMinutes: 5,
    author: "Sofia Patel",
    body: [
      "Some changes begin as a question that is specific enough to answer.",
      "What happens to the untouched food? Can we put a second bin here? Is there a way to bring an extra serving home? Who should we ask before we make a plan?",
      "Asking does not mean waiting for permission forever. It means finding the person who knows the next door to open. One question can turn a private worry into a shared project.",
      "This week, ask one useful question. Then write down the answer and bring it to someone else.",
    ].join("\n\n"),
    tags: ["studentaction", "askbetter", "school"],
    status: "published",
    publishedAt: new Date("2024-09-04T12:00:00.000Z"),
  },
];

export async function seedStories(): Promise<void> {
  await db.insert(storiesTable).values(seededStories).onConflictDoNothing({ target: storiesTable.slug });
}